spring:
  application:
    name: myjpastudy

  # datasource:
  #     url: jdbc:mysql://localhost:3306/(Connection명)
  #     driver-class-name: com.mysql.cj.jdbc.Driver
  #     username: root
  #     password: ''

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: mysql
